name: Waka Readme

on:
  schedule:
    - cron: "30 * * * *" # runs every 30 minutes
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with WakaTime stats
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: "FALSE"
          SHOW_PROFILE_VIEWS: "FALSE"
          SHOW_LINES_OF_CODE: "FALSE"
          SHOW_SHORT_INFO: "FALSE"
          SHOW_LOC_CHART: "FALSE"
          SHOW_PROJECTS: "FALSE"
          SHOW_LANGUAGE: "TRUE"
          SHOW_OS: "FALSE"
          SHOW_EDITORS: "FALSE"
          SHOW_TIMEZONE: "FALSE"
          SHOW_COMMIT: "FALSE"
          SHOW_DAYS_OF_WEEK: "FALSE"
          SHOW_LANGUAGE_PER_REPO: "FALSE"
          SHOW_UPDATED_DATE: "FALSE"
          COMMIT_MESSAGE: "update wakatime stats"
